spring.application.name=agentbox-platform

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/agentbox?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# application.yml
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# H2 Console
spring.h2.console.enabled=true


spring.ai.dashscope.api-key=sk-ad3ba45effd748bbb56f0b90029ba506
spring.ai.dashscope.chat.model=qwen-turbo
spring.ai.dashscope.chat.temperature=0.7


spring.ai.deepseek.api-key=sk-60df0b07edf14cff8fd66a65f65caa14
spring.ai.deepseek.chat.model=deepseek-r1
spring.ai.deepseek.chat.temperature=0.7
spring.ai.deepseek.base-url=https://api.deepseek.com

# MyBatis-Plus
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.id-type=auto